version: '3.8'

services:
  music-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-web-application
    stop_grace_period: 45s
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8080:8080"
    env_file:
      - .env

   # Docker-level logging (catches crashes before app writes to file)
    logging:
        driver: "json-file"
        options:
          max-size: "50m"
          max-file: "5"
          compress: "true"
    environment:
      # Cloud Database Configuration
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # Upstash Redis
      - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
      - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_DATA_REDIS_USERNAME=${REDIS_USERNAME}
      - SPRING_DATA_REDIS_SSL_ENABLED=true

      # JWT Secret
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

      # AWS S3 Configuration
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-us-east-1}

      # Email Configuration
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      # Url Config
      - BASE_URL=${BASE_URL}

      # Cache directory
      - APP_CACHE_DIR=/app/song-cache

    networks:
      - music-network
    volumes:
      - song-cache:/app/song-cache
      - ./logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

# Networks
networks:
  music-network:
    driver: bridge

# Volumes
volumes:
  song-cache:
    driver: local