spring.application.name=music-web-application
#jwt
jwt.security.secret-key=your-very-secret-key-that-is-at-least-256-bits-long-change-this-in-production-12345678

# H2 Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/music
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=******
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#SQL query audit
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.batch.jdbc.initialize-schema=always
#S3
cloud.aws.credentials.access-key =************
cloud.aws.credentials.secret-key =*******************
cloud.aws.region.static =ap-south-1
# Maximum file size for individual files (default is 1MB)
spring.servlet.multipart.max-file-size=100MB

# Maximum request size for multipart/form-data (default is 10MB)
spring.servlet.multipart.max-request-size=100MB
aws.bucket.name=tony-music-bucket

#thymelaf properties
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

##loging
#logging.level.com.music.musicwebapplication=ERROR
#logging.level.org.springframework.messaging=DEBUG
#logging.level.org.springframework.web.socket=DEBUG